application: backlog
version: 1

runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py

